# ----------------------------------------------------- 
# ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█
#
# name "End4"
# credit https://github.com/end-4/dots-hyprland
# ----------------------------------------------------- 

animations {
    enabled = true

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 3.8, myBezier
    animation = windowsIn, 1, 4.2, myBezier, slide
    animation = windowsOut, 1, 4.2, default, slide
    animation = border, 1, 6, default
    animation = borderangle, 1, 5, default
    animation = fade, 1, 4.5, default
    animation = workspaces, 1, 4, default
}
