##############################
### WINDOWS AND WORKSPACES ###
##############################

# Ignore maximize requests from apps
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrule = opacity 0.90 $& 0.90 $& 1,class:^(kitty)$
windowrule = opacity 0.90 $& 0.90 $& 1,class:^(nemo)$
windowrule = opacity 0.80 $& 0.70 $& 1,class:^(org.pulseaudio.pavucontrol)$
windowrule = opacity 0.80 $& 0.70 $& 1,class:^(blueman-manager)$
windowrule = opacity 0.80 $& 0.70 $& 1,class:^(nm-applet)$
windowrule = opacity 0.80 $& 0.70 $& 1,class:^(nm-connection-editor)$

# --- Floating rules ---
windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = float,class:^(nm-connection-editor)$
windowrulev2 = float,class:^(nm-applet)$
windowrulev2 = float,class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = center,class:^(blueman-manager)$
windowrulev2 = size 600 400,class:^(blueman-manager)$
windowrulev2 = size 800 1000,class:^(Xdg-desktop-portal-gtk)$

layerrule = blur,waybar
layerrule = blur,wofi
