[spotify]
extra_arguments = [
  "--enable-features=UseOzonePlatform",
  "--ozone-platform=wayland",
  "--enable-zero-copy",
  "--disable-smooth-scrolling",
  "--enable-gpu-rasterization",
  "--enable-accelerated-video-decode"
]
